"use client";
import "./styles/globals.css";
import ClientProviders from "./context/ClientProvider";
import Header from "./_components/layout/header";
import Footer from "./_components/layout/footer";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: any;
}) {
  return (
    <html lang="en">
      <ClientProviders session={session}>
        <Header />
        <body>{children}</body>
        <Footer />
      </ClientProviders>
    </html>
  );
}
